version: "3.9"

services:
  uts_mysql:
    image: mysql:8.0
    container_name: uts_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_uts
      MYSQL_DATABASE: uts_mysql_db
      MYSQL_USER: uts_user
      MYSQL_PASSWORD: uts_password
    networks:
      uts_internal_net:
        ipv4_address: 172.30.14.10
    restart: unless-stopped

  uts_postgres:
    image: postgres:15
    container_name: uts_postgres
    environment:
      POSTGRES_DB: uts_postgres_db
      POSTGRES_USER: uts_user
      POSTGRES_PASSWORD: uts_password
    networks:
      uts_internal_net:
        ipv4_address: 172.30.14.20
    restart: unless-stopped

  uts_adminer:
    image: adminer
    container_name: uts_adminer
    ports:
      - "10.147.20.123:8014:8080"
    networks:
      uts_internal_net:
        ipv4_address: 172.30.14.30
    restart: unless-stopped

networks:
  uts_internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.14.0/24
